### ISSUE TITLE
OSError happened when use windnd

### ISSUE THREAD

**Issue by yunlongYoung** [cilame/windnd#1]
when I use windnd on win10 (python 3.8.1), a error ocurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Users\drago\AppData\Local\Programs\Python\Python38\lib\site-packages\windnd\windnd.py", line 85, in py_drop_func
    return ctypes.windll.user32.CallWindowProcW(*map(argtype,(globals()[old],hwnd,msg,wp,lp)))
OSError: exception: access violation writing 0xFFFFFFFFEB395CF0

I found some webpage wrote by others had this problem like me.
https://blog.51cto.com/ikezcn/2142638
https://blog.csdn.net/LiangJohnny/article/details/79896796?utm_source=blogxgwz5

**Comment by liwancheng91** [comment]
I have the same error in win7 (python3.7.0)
a temp solution: change Python to 3.6.8, it's OK

**Comment by cilame** [comment]
> when I use windnd on win10 (python 3.8.1), a error ocurred:
> 
> Traceback (most recent call last):
> File "_ctypes/callbacks.c", line 237, in 'calling callback function'
> File "C:\Users\drago\AppData\Local\Programs\Python\Python38\lib\site-packages\windnd\windnd.py", line 85, in py_drop_func
> return ctypes.windll.user32.CallWindowProcW(*map(argtype,(globals()[old],hwnd,msg,wp,lp)))
> OSError: exception: access violation writing 0xFFFFFFFFEB395CF0
> 
> I found some webpage wrote by others had this problem like me.
> https://blog.51cto.com/ikezcn/2142638
> https://blog.csdn.net/LiangJohnny/article/details/79896796?utm_source=blogxgwz5

fix bug in 1.0.6.

**Comment by cilame** [comment]
> I have the same error in win7 (python3.7.0)
> a temp solution: change Python to 3.6.8, it's OK

fix bug in 1.0.6.

**Comment by wonderain** [comment]
Hello, I have a question when use windnd, and can't deal by myself(I‘m new to programming）:
function 'hook_dropfiles' can't get a unicode(or other type?) character like '♥' in dirpath, so that I can't get a correct dirpath to use for other functions.
I think it may be due to  these sentences : 'szFile = ctypes.c_buffer(260)' and 'ctypes.windll.shell32.DragQueryFile(argtype(wp),i,szFile,ctypes.sizeof(szFile))' in your program.
Could u plz answer or solve this problem. Sorry to bother you.
By the way, I find the comment in program writed in Chinese.....so : 能教教我嘛，老哥？先谢谢你的代码啦！

**Comment by cilame** [comment]
> Hello, I have a question when use windnd, and can't deal by myself(I‘m new to programming）:
> function 'hook_dropfiles' can't get a unicode(or other type?) character like '♥' in dirpath, so that I can't get a correct dirpath to use for other functions.
> I think it may be due to these sentences : 'szFile = ctypes.c_buffer(260)' and 'ctypes.windll.shell32.DragQueryFile(argtype(wp),i,szFile,ctypes.sizeof(szFile))' in your program.
> Could u plz answer or solve this problem. Sorry to bother you.
> By the way, I find the comment in program writed in Chinese.....so : 能教教我嘛，老哥？先谢谢你的代码啦！

fix in 1.0.7 更新版本即可。 hook_dropfiles 函数增加了一个新的参数 hook_dropfiles(tk, force_unicode=True)，这样可以解决你的特殊符号的问题。

**Comment by wonderain** [comment]
非常感谢你的解答！解决问题了
